package baseAPI.API.Sistema.Enum;

public enum SelecionarAcaoBackup {

    NOVO_CLIENTE,
    EDITAR_CLIENTE,
    NOVO_COLABORADOR,
    EDITAR_COLABORADOR,
    NOVO_FORNECEDOR,
    EDITAR_FORNECEDOR,
    NOVO_ORCAMENTO,
    EDITAR_ORCAMENTO,
    NOVA_ORDEM_SERVICO,
    ATUALIZACAO_ORDEM_SERVICO,
    FINALIZACAO_ORDEM_SERVICO;
}
